"use client";
import { useEffect, useState } from "react";
import { marked } from "marked";
import { usePost } from "@/hooks/use-post";
import PostReadingProgress from "../../components/shared/reading-progress";

// Configure marked
marked.setOptions({
  breaks: true,
  gfm: true,
});

export default function ReportViewPage() {
  const { post } = usePost();
  const [htmlContent, setHtmlContent] = useState('');
  
  useEffect(() => {
    if (post?.content) {
      // Better extraction preserving line breaks
      const tempDiv = document.createElement('div');
      tempDiv.innerHTML = post.content;
      
      // Get text while preserving structure
      let markdownText = '';
      const processNode = (node: Node) => {
        if (node.nodeType === Node.TEXT_NODE) {
          markdownText += node.textContent;
        } else if (node.nodeName === 'BR') {
          markdownText += '\n';
        } else if (node.nodeName === 'P') {
          if (node.textContent) {
            markdownText += node.textContent + '\n\n';
          }
        } else if (node.childNodes) {
          node.childNodes.forEach(processNode);
        }
      };
      
      tempDiv.childNodes.forEach(processNode);
      
      console.log('Extracted markdown:', markdownText.substring(0, 500));
      
      // Convert markdown to HTML
      const html = marked.parse(markdownText);
      setHtmlContent(html as string);
    }
  }, [post]);
  
  if (!post) return null;

  return (
    <article className="min-h-screen bg-white dark:bg-gray-900 py-8 px-6">
      <PostReadingProgress />
      
      <div className="max-w-4xl mx-auto">
        {/* Report Header */}
        <div className="mb-8 pb-6 border-b border-gray-200">
          <h1 className="text-3xl font-bold mb-2 text-gray-900 dark:text-white">
            {post.title}
          </h1>
          <div className="flex gap-3 text-sm text-gray-600 dark:text-gray-400">
            <span>Strategy Report</span>
            <span>•</span>
            <span>{post.readingTime} min read</span>
            <span>•</span>
            <span>{new Date(post.createdAt).toLocaleDateString()}</span>
          </div>
        </div>

        {/* Report Content */}
        <div 
          className="prose prose-base max-w-none
            prose-headings:font-semibold
            prose-h1:text-2xl prose-h1:mb-3 prose-h1:mt-6
            prose-h2:text-xl prose-h2:mb-2 prose-h2:mt-5
            prose-h3:text-lg prose-h3:mb-2 prose-h3:mt-4
            prose-p:mb-3 prose-p:leading-relaxed prose-p:text-gray-700
            prose-a:text-blue-600 hover:prose-a:underline
            prose-strong:font-semibold
            prose-ul:my-3 prose-ul:list-disc prose-ul:pl-6
            prose-li:mb-1.5
            prose-table:border-collapse prose-table:w-full prose-table:my-4
            prose-th:bg-gray-50 prose-th:p-2 prose-th:text-left prose-th:text-sm prose-th:border
            prose-td:p-2 prose-td:text-sm prose-td:border"
          dangerouslySetInnerHTML={{ __html: htmlContent }}
        />
        
        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-gray-200 text-center text-sm text-gray-500">
          <p>Generated by AI-Powered Strategy Report System</p>
          <p className="text-xs mt-1">Powered by Tiptap AI Agent & GPT-4o</p>
        </div>
      </div>
    </article>
  );
}